name: deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Deploy to xmit
        run: npx @xmit.co/xmit tairesh.xmit.dev@${{ secrets.XMIT_TEAM }}
        env:
          XMIT_KEY: ${{ secrets.XMIT_TOKEN }}
