name: validate

on:
  push:
    paths:
      - '**.html'
      - '**.css'
      - '**.js'
      - 'eslint.config.mjs'
  pull_request:
    paths:
      - '**.html'
      - '**.css'
      - '**.js'
      - 'eslint.config.mjs'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Node
        uses: actions/setup-node@v7

      - name: Set up Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Just
        uses: extractions/setup-just@v4

      - name: Validate HTML, CSS and JS
        run: just validate
